variable "aws_region" {}
variable "aws_profile" {}
variable "environment" {}
variable "cluster_name" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "eks_node_group_single_az" {}
variable "public_subnets_cidr" {}
variable "availability_zones_public" {}
variable "private_subnets_cidr" {}
variable "availability_zones_private" {}
variable "cidr_block-internet_gw" {}
variable "cidr_block-nat_gw" {}
variable "eks_node_group_arm_architecture" {}
variable "eks_node_group_instance_types" {}
variable "eks_node_group_capacity_type" {}
variable "eks_node_group_disk_size" {}
variable "eks_node_group_scaling_desired_size" {}
variable "eks_node_group_scaling_max_size" {}
variable "eks_node_group_scaling_min_size" {}
